from __future__ import annotations

import secrets
from datetime import UTC, datetime
from pathlib import Path
from typing import Callable


DEFAULT_P5_SECRET_BYTES = 32


def build_p5_security_bootstrap(
    *,
    include_admin_token: bool = True,
    include_static_mcp_token: bool = False,
    token_bytes: int = DEFAULT_P5_SECRET_BYTES,
    token_factory: Callable[[int], str] | None = None,
) -> dict:
    if token_bytes < 16 or token_bytes > 128:
        raise ValueError("token_bytes must be between 16 and 128")
    factory = token_factory or secrets.token_urlsafe
    env = {
        "CODEKB_DIAGNOSE_WEBHOOK_TOKEN": factory(token_bytes),
        "CODEKB_IM_OAUTH_STATE_SECRET": factory(token_bytes),
    }
    if include_admin_token:
        env["CODEKB_AUTH_ADMIN_TOKEN"] = factory(token_bytes)
    warnings: list[str] = [
        "Store these values in a server-side environment file with 0600 permissions.",
        "Do not commit generated secret values to the repository.",
        "Restart the API and MCP/confirmation workers after applying changed environment variables.",
    ]
    if include_static_mcp_token:
        env["CODEKB_MCP_TOKEN"] = factory(token_bytes)
        warnings.append(
            "CODEKB_MCP_TOKEN is for local diagnose smoke only; production MCP should use token-store auth, "
            "and static tokens are ignored when --token-store is configured."
        )
    return {
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "env": env,
        "warnings": warnings,
        "next_steps": [
            "Set CODEKB_DIAGNOSE_WEBHOOK_TOKEN and require X-CodeKB-Token on webhook callers.",
            "Set CODEKB_IM_OAUTH_STATE_SECRET before enabling IM OAuth login.",
            "Configure CODEKB_IM_CORP_ID/AGENT_ID/APP_SECRET from the IM app console.",
            "Run diagnose-readiness after applying configuration.",
        ],
    }


def render_p5_security_env(payload: dict) -> str:
    lines = [
        "# Generated by codekb diagnose-security-bootstrap",
        "# Store server-side only. Do not commit this file.",
    ]
    for key, value in dict(payload.get("env") or {}).items():
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def write_p5_security_env_file(path: str | Path, content: str, *, force: bool = False) -> None:
    output = Path(path)
    if output.exists() and not force:
        raise ValueError(f"output file already exists: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    output.chmod(0o600)
